services:
  - type: web
    name: hrms-app
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install && npm --prefix server run build
    startCommand: node server/server.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: SEED_USERNAME
        sync: false
      - key: SEED_PASSWORD
        sync: false
      - key: SEED_ROLE
        value: admin
