[build]
# No bundling step; publish the site root where index.html, styles.css, app.js live
publish = "."
command = ""

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# Send /api/* to our single serverless function
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true
