[build]
  command = "npm --prefix server install && npm --prefix server run build && npm run build"
  publish = "public/dist"      # change to your frontend build output
  base = ""                    # set if monorepo subdir

[dev]
  command = "netlify dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
